// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {i18n} from '../models';
import {context} from '../models';

export function ApplySettings(arg1:domain.Settings):Promise<void>;

export function GetActivationState():Promise<domain.WindowActivationState>;

export function GetDefaultSettings():Promise<domain.Settings>;

export function GetSettings():Promise<domain.Settings>;

export function GetState():Promise<domain.RuntimeState>;

export function GetSupportedLanguages():Promise<Array<i18n.Language>>;

export function GetTranslations(arg1:string):Promise<Record<string, string>>;

export function GetWindowList():Promise<Array<domain.WindowInfo>>;

export function RequestQuit():Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function SetTrayCallback(arg1:any):Promise<void>;

export function ShowWindow():Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SyncWindowLayout(arg1:boolean,arg2:boolean):Promise<void>;
