// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplySettings(arg1) {
  return window['go']['app']['App']['ApplySettings'](arg1);
}

export function GetActivationState() {
  return window['go']['app']['App']['GetActivationState']();
}

export function GetDefaultSettings() {
  return window['go']['app']['App']['GetDefaultSettings']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetSupportedLanguages() {
  return window['go']['app']['App']['GetSupportedLanguages']();
}

export function GetTranslations(arg1) {
  return window['go']['app']['App']['GetTranslations'](arg1);
}

export function GetWindowList() {
  return window['go']['app']['App']['GetWindowList']();
}

export function RequestQuit() {
  return window['go']['app']['App']['RequestQuit']();
}

export function SetEnabled(arg1) {
  return window['go']['app']['App']['SetEnabled'](arg1);
}

export function SetTrayCallback(arg1) {
  return window['go']['app']['App']['SetTrayCallback'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function Shutdown(arg1) {
  return window['go']['app']['App']['Shutdown'](arg1);
}

export function SyncWindowLayout(arg1, arg2) {
  return window['go']['app']['App']['SyncWindowLayout'](arg1, arg2);
}
